### ISSUE TITLE
Improve signoff

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#102]
- [x] remove quotes, they're noisy and don't seem necessary (git commit -s doesn't quote)
- [x] it's unclear that we're using it properly, [according to the kernel documentation](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/process/submitting-patches.rst?id=HEAD#n416) this looks more like sign-off is a CLA-equivalent? /cc @KangOl

**Comment by KangOl** [comment]
[git documentation](https://git-scm.com/docs/git-commit#git-commit--s) says that *the meaning of a signoff depends on the project*. So, there is no improper use of it (as long as we are consistent)

**Comment by xmo-odoo** [comment]
@KangOl fair enough.
