### ISSUE TITLE
Automatic or requested reviewer / assignee on PR

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#110]
GH currently doesn't have split rights between the code and issues / PR part of a repository:

> Improving permissions is something the team would like to implement in the future. There are some discussions happening within the Engineering and Product Teams and I believe one of those points is adding separate permissions for Issues.

> We'll pass your feedback onto the team to consider.

This means external contributors or new employees can't be empowered with assigning folks or requesting reviews<sup id="source0">[0](#fn0)</sup> without also giving them write access to the repository, and we can't further reduce write access to the main repositories without creating more issues.

Commands could be added to @robodoo (or to an other bot drafted for the occasion e.g. @C3POdoo should already have the necessary rights and avoid the extended rights @robodoo needs for its own work) though this requires either that anyone can use the assigner bot<sup id="source1">[1](#fn1)</sup> or that employees and contributors get opted in manually (similar to @robodoo but worse).

A relatively easy option would be to use [highfive](https://github.com/rust-lang/highfive), which can auto-assign (based on directories & stuff) but is overridable (`r? <username>` will change the assignee to that). As far as I can tell we'd still have to deploy our own with whatever bot / user we want as it's not a GH application we can just install on the repo (and we might want our own customisations e.g. highfive seems to only handle assigning PRs, we may want reviews as well? ![notsure](https://user-images.githubusercontent.com/7571158/54757793-3d56b080-4beb-11e9-8b91-10609b0d2d4d.png)).

/cc @odony @JKE-be 

<b id="fn0">[0]</b>: which some teams use in their own workflows  [↩](#source0)

<b id="fn1">[1]</b>: not necessarily a huge issue especially if we can blacklist abusers  [↩](#source1)

**Comment by xmo-odoo** [comment]
Of note, working on the forwardbot I (re)discovered that there are pretty strict limitations on assigning people to PRs (not sure about review requests): only repository "contributors" (?) or people which have interacted with (commented on?) the PR can be assigned.

**Comment by Xavier-Do** [comment]
Can we consider this outdated with the codeowner added to runbot?
