### ISSUE TITLE
Unable to find image 'odoo:runbot_tests'

### ISSUE THREAD

**Issue by aliencrash** [odoo/runbot#113]
While I try to run runbot, it cannot download odoo:runbot_tests
Unable to find image 'odoo:runbot_tests' locally
Trying to pull repository docker.io/library/odoo ... 
Trying to pull repository registry.fedoraproject.org/odoo ... 
Trying to pull repository quay.io/odoo ... 
Trying to pull repository registry.access.redhat.com/odoo ... 
Trying to pull repository registry.centos.org/odoo ... 
Trying to pull repository docker.io/library/odoo ... 
/usr/bin/docker-current: manifest for docker.io/odoo:runbot_tests not found.
See '/usr/bin/docker-current run --help'.

**Comment by Xavier-Do** [comment]
Since you answered to #159, I guess you solved your problem?
