### ISSUE TITLE
clean up of logs when job_end hasn't been filled on build

### ISSUE THREAD

**Issue by sts-odoo** [odoo/runbot#114]
When for whatever reason job_end on the build has not been filled, the clean-up will not count it as active. Might be worth it to add a OR condition based on the create date of the build and not only on the last modification date of the log file.
As the log files are cleaned up, it's actually more difficult to read them when the logs are non existing :-)

**Comment by Xavier-Do** [comment]
Some fix have been done concerning job_end. Everything should be ok now, tell me if you still have a the problem with last version.
