### ISSUE TITLE
Detect noop PRs

### ISSUE THREAD

**Issue by KangOl** [odoo/runbot#179]
Some PRs does not need to be tested as they are known to do not change the build status.
If a PR doesn't change tested code, there is no need to fully test it.

PRs to ignore:
 - If only `doc/` directory is modified. This includes the "CLA" PRs.
 - If only ignored modules modified, like "l10n_*" modules.
 - maybe other cases.

**Comment by Xavier-Do** [comment]
- We are thinking about building the doc as a test in the future
- l10n is tested in some case like nightly, or specific config for devs used by jco and other
- we want to add tests for commit messages so even if no test is run we need to do that
See https://github.com/odoo/runbot/issues/109

This would need to identify changes needed per test set, and this can change between versions I think so it is quite difficult to do without hard coding some hazardous logic, maybe latter but this isn't a priority. 
I think that for few case when this happen, we can wait for the test to be passed. We could also ask @xmo-odoo to add a p -1 on mergebot maybe if we really want to be able to merge this kind of change faster.
