### ISSUE TITLE
Better UX for "no forward port"

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#191]
odoo/odoo#36614 tried to set the limit to 10.0 in order to cancel forward-port. However at that point 10.0 was not configured as an FP target (I didn't think it would be useful as 10.0 would be the "root" and source of all FPs but never an actual target).

**Comment by KangOl** [comment]
something like `@fw-bot stop`?

**Comment by xmo-odoo** [comment]
Stopping before having started is a bit odd.

I was thinking of special-casing the current PR's target to start with, and maybe an "ignore" command or something like that..
