### ISSUE TITLE
Check that PRs in errors are properly closed when closing them

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#227]
odoo/odoo#37825 was closed by @nim-odoo while in staging error, but that apparently didn't get signalled to the backend? It's still in error there.

**Comment by nim-odoo** [comment]
Hum I closed it because the v13 version was merged: https://github.com/odoo/odoo/pull/37835

**Comment by xmo-odoo** [comment]
Turns out I don't have any logging on the closed event currently, so I can't know whether we ignored the signal or we didn't get it at all (though I'd expect the latter).

Anyway closing and adding logging, hopefully next time around I'll have more data, as it seems to be an irregular not that uncommon occurrence: issue was also hit on odoo/odoo#37467 and odoo/enterprise#5894
