### ISSUE TITLE
Incorrect PR / name format in case of merge or rebase-merge PRs

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#229]
On forward-porting multi-commit PRs with a mode of merge or rebase-merge, because forwardbot creates PRs of the form "Forward Port of #<source> to <branch>", which will then become an incorrect commit message.

Cf #6004 odoo/enterprise@73c2025aba062e8b9403df0bd5a8817bf3db8412

/cc @Xavier-Do who saw that
/cc @nim-odoo so you're aware of that issue

**Comment by nim-odoo** [comment]
Prepend [FW] to original title and get naked
