### ISSUE TITLE
Mergebot could include references to matching odoo/odoo commit and/or PR when merging an odoo/enterprise PR

### ISSUE THREAD

**Issue by odony** [odoo/runbot#238]
It's impossible for the developer to do it manually, as the commit hash changes during merge, yet having a direct link to the matching patch is very handy.

It's a bit similar to the `X-original-commit` link that is included by the fwdbot, but more complicated because there may be different numbers of commits (rebase-merge, rebase-ff, etc)

If the link to the commit is too difficult to maintain across retries, an automatic link to the matching PR would still be great to have. :D

**Comment by Xavier-Do** [comment]
Link to the matching pr if exist would be easy to do I guess.

Finding the corresponding community commit is less obvious when merged in batch, but finding a compatible commit would correspond to:
- Find the corresponding successful enterprise staging commit uniquifier: ex: https://github.com/odoo/enterprise/commit/d3fd2c8319262bfb54b5ace46bf3853bdfd8795f
- Staging commit has a corresponding Runbot-dependency: odoo/odoo:839dc2bddbd2fd9fca9b1123ffbe4e424dc99f 
- The HEAD^ of this commit is the one that is merged in community, compatible with the merged batch.

We could also try to find a commit in the batch that closes the corresponding community pr if there is one.

**Comment by odony** [comment]
:tada: Thanks!
