### ISSUE TITLE
Error while building the docker file image

### ISSUE THREAD

**Issue by aliencrash** [odoo/runbot#249]
While trying to create a build in the build folder the docker log show the following error. I've tested the Dockerfile by executing with docker and I get the same issue. It's not possible to instantiate the image to create a container

Err:169 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 x11-common all 1:7.7+19ubuntu7.1
  Connection timed out [IP: 91.189.88.174 80]
Get:170 http://archive.ubuntu.com/ubuntu bionic/main amd64 xfonts-encodings all 1:1.0.4-2 [573 kB]
Get:171 http://archive.ubuntu.com/ubuntu bionic/main amd64 xfonts-utils amd64 1:7.7+6 [91.5 kB]
Get:172 http://archive.ubuntu.com/ubuntu bionic/universe amd64 xfonts-75dpi all 1:1.0.4+nmu1 [3368 kB]
Get:173 http://archive.ubuntu.com/ubuntu bionic/main amd64 zip amd64 3.0-11build1 [167 kB]
Get:174 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libldap2-dev amd64 2.4.45+dfsg-1ubuntu1.4 [262 kB]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/m/mpfr4/libmpfr6_4.0.1-1_amd64.deb  Connection timed out [IP: 91.189.88.149 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/heimdal/libasn1-8-heimdal_7.5.0+dfsg-1_amd64.deb  Connection timed out [IP: 91.189.88.24 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/h/heimdal/libkrb5-26-heimdal_7.5.0+dfsg-1_amd64.deb  Connection timed out [IP: 91.189.88.24 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-2.4-2_2.4.45+dfsg-1ubuntu1.4_amd64.deb  Connection timed out [IP: 91.189.88.24 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/z/zlib/zlib1g-dev_1.2.11.dfsg-0ubuntu2_amd64.deb  Connection timed out [IP: 91.189.88.174 80]
Fetched 231 MB in 9min 1s (427 kB/s)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/x/xorg/x11-common_7.7+19ubuntu7.1_all.deb  Connection timed out [IP: 91.189.88.174 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c set -x ;     apt-get update     && apt-get install -y --no-install-recommends     apt-transport-https     build-essential     ca-certificates     curl     fonts-freefont-ttf     fonts-noto-cjk     gawk     gnupg     libldap2-dev     libsasl2-dev     libxslt1-dev     node-less     python     python-dev     python-pip     python3     python3-dev     python3-pip     python3-setuptools     python3-wheel     sed     sudo     xfonts-75dpi     zip     zlib1g-dev' returned a non-zero code: 100

**Comment by Xavier-Do** [comment]
It looks more like a network problem on your side, nothing of this looks runbot related.
