### ISSUE TITLE
Feedback that r- on a p=0 pr is not useful

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#313]
R- will unstage the pr but since p=0 overrode status it’s going to get restaged immediately.

**Comment by nim-odoo** [comment]
It could be reset to 2, with an informative message.

**Comment by xmo-odoo** [comment]
@nim-odoo works for me. Maybe just to 1 so it's still prioritised once it gets r+'d (assuming the p=0 was there for a good reason), but it doesn't bypass review/ci anymore?

**Comment by nim-odoo** [comment]
Good for me as long as the informative message is clear enough on what is going on.
