### ISSUE TITLE
Link theme repo + robodoo

### ISSUE THREAD

**Issue by rdeodoo** [odoo/runbot#337]
As previously discussed `design-themes` repo need to be added on runbot build so any community and/or enterprise branch breaking themes will be red.
Must have been a misunderstanding because I thought it was done recently.

Also, we need robodoo on `design-themes`, as you might have seen the repo is not green anymore, robodoo would have prevented that.

**Comment by JKE-be** [comment]
+100000000000

**Comment by Xavier-Do** [comment]
Upgrade was the priority, design themes is coming next but we first need it to be green ;)

**Comment by d-fence** [comment]
Sorry, for the misunderstanding but we were waiting it to be green, that was not the case at freeze time.

**Comment by rdeodoo** [comment]
Fix is coming at https://github.com/odoo/odoo/pull/46292
We will ping you as soon as the themes repo are green again
cc @sdegueldre

**Comment by d-fence** [comment]
ok

**Comment by rdeodoo** [comment]
Theme runbot is green in 13.2 and will be green in master once the [forward port](https://github.com/odoo/odoo/pull/46387) is merged in community.
Btw, the reason a fix was needed in community to make themes green is because of the `test_themes` module in `design-themes` which is installing every themes to ensure they load correctly.
Obviously, it was not the case because of a change in community.
Anything in community can easily breaks the themes, variable name change etc, since most people don't have `design-themes` loaded in IDE and any search/replace won't return `design-themes` results.
Hopefully, this won't be the case anymore soon :+1:

**Comment by d-fence** [comment]
Done
