### ISSUE TITLE
Add a "close" command on the fw-bot

### ISSUE THREAD

**Issue by madprog** [odoo/runbot#341]
Until today, I wasn't in the `rd` team, so I had a limited access to `odoo/odoo` and only saw the Close button if I was the author of a pull request.

I happened to get a conflict on a forwarded port, because the patched file was removed in saas-13.1.
The result was that odoo/odoo#46611 was created, but I wanted to close it and couldn't because of my limited permissions.

The feature I imagine here is to add the command `@fw-bot close` that would allow to close a fw-bot-generated PR instead. This command would be accepted from the same people that can also do a `@fw-bot r+`.

**Comment by xmo-odoo** [comment]
That does make sense.

**Comment by madprog** [comment]
:tada:
