### ISSUE TITLE
how to setup

### ISSUE THREAD

**Issue by alfadil** [odoo/runbot#360]
can anyone please give me the tips to setup your runbot?

**Comment by obayit** [comment]
@alfadil What is the step that you are stuck in?

**Comment by alfadil** [comment]
> @alfadil What is the step that you are stuck in?
> 
> **Edit**
> I just realised that this was 5 months ago :/

thanks for replying 
still no official documentation about how to setup it.
@obayit if you have any steps to configure it that would be great 
thank you again for you replay

**Comment by obayit** [comment]
See this [documentation](https://www.odoo.yenthevg.com/installing-and-configuring-your-own-runbot/) made by our good friend yenthe. I don't have anything to add to his steps, but if you are stuck on a specific problem I might be able to help :)

**Comment by Xavier-Do** [comment]
@alfadil The new runbot has an included readme to help you for setup.

**Comment by alfadil** [comment]
> See this [documentation](https://www.odoo.yenthevg.com/installing-and-configuring-your-own-runbot/) made by our good friend yenthe. I don't have anything to add to his steps, but if you are stuck on a specific problem I might be able to help :)

I tried it before but without any successful results, I remember there was a lost point in the process

**Comment by alfadil** [comment]
> @alfadil The new runbot has an included readme to help you for setup. 

That new!
I will give it a try
Thanks 👍

**Comment by Xavier-Do** [comment]
> That new!
> I will give it a try
> Thanks

Yes it was merged yesterday. The readme is maybe not perfectly up to date so feel free to report problems/ask question if it isn't clear enough.
