### ISSUE TITLE
mergebot improvements

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#38]
## selected todos
- [x] clarify dashboard / staging status

  staging `state` is just the runbot notification, however things get a bit odd when a staging is cancelled (usually because one of the PRs is closed/updated while being staged): the staging is active=False so it's never marked as Success or Failure because it's not found when updating CI state. This is an opportunity: a computed `status` field can have all the states of `state` + "cancelled" when `state=='pending' and not active`
- [x] Allow `@` prefix to bot

  People are used to `@`-call others, they might do that for the mergebot user, but the bot currently expect command lines to start with its own name (and that only). It should allow being `@`-ed for wetware compatiblity
- [x] flag stagings when fast-forward failed, currently the build is disabled but looks successful (since the statuses passed) fixed with #41 
## ideas (to decide)

-  ~~Ask for multiple reviews, currently a review by a reviewer is "binding". Delegating reviews does handle some cases of multi-review, but more flexibility might be useful?~~
- Automatically remove branch when merged (when stable enough, though) [NIM]

  [xmo]: should probably be a separate tool instead, deletion conditions TBD.
- Better handle reopening: currently re-creates the PR in "opened" mode, even if the PR previously passed review & CI, maybe check for that? Alternatively: a ping/check signal for the mergebot to completely reload the PR?
- add github rate limit to dashboard

  github has a rate limit of 5000 requests/h. Assuming 1 staging/h/branch (1h is about the time for an enterprise staging to get tested ATM), 8 batches/staging, 10 branches and 2 repos gives us \~160PRs/h if the pipeline is always full, or a limit of \~31 queries/PR staged. Squash and merge don't come close (they're on the order of 3\~6 queries I'd say) so we should be fine, but keeping an eye on it might still be useful (rebase & merge is 2 queries / commit + a baseline of 3\~4 so rebase-merging PRs with many commits could easily be above 50, though that should be a very rare event).
- add [CacheControl](https://cachecontrol.readthedocs.io/en/latest/)

  The risk of hitting rate limits is low (cf above) but when staging & restaging we might fetch the same PR info several times. Github does recommend using [conditional requests](https://developer.github.com/v3/#conditional-requests). A wrinkle here is we might do these fetches on different runbot instances so would need do implement & use a shared cache in postgres for it to really be useful.

**Comment by mreficent** [comment]
@xmo-odoo Something that bothers me is that the commits merged with robodoo has as date the pushing commit date instead of the merging date. And that bother me because if some old PR is merged with robodoo, I will not find the merged commits in the end of the branch, I will have to dive into the historial of commits until the date of the push to find them. I wonder if this behavior is intended or not.

**Comment by xmo-odoo** [comment]
@mreficent That's a github-specific behaviour, where most tools display the history topologically, github does so based on the date metadata.

Keeping the commit metadata as-is is the currently intended behaviour, though it's not impossible to eventually change it.

**Comment by mreficent** [comment]
@xmo-odoo ok, thanks for your answer. My vote is for not keeping the date metadata and change it for the merging date 😜
