### ISSUE TITLE
Block PRs which still contain conflict messages.

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#380]
odoo/odoo@ce67acc1ba4a91682e2d4ebbbdfb96b1be87b8df reported by @JKE-be

- [ ] don't stage if any of the PR's commits contains a conflict message
- [ ] remove approver's review rights on the PR? there's no "negative delegations" so users with "persistent" review rights can't easily have them removed

**Comment by xmo-odoo** [comment]
@d-fence would the new runbot thing allow easily creating a lint / status for this rather than have to integrate it into the mergebot (where I really don't think it belongs)?

**Comment by d-fence** [comment]
Hmm, we already have [this test](https://github.com/odoo/odoo/blob/11.0/odoo/addons/test_lint/tests/test_markers.py)
But I think that a particular CI could be possible with the new runbot

**Comment by xmo-odoo** [comment]
@d-fence yeah but here the issue was that the user fixed the code conflict of a multi-commit PR straight in there instead of following the instructions and properly re-doing the cherrypicking, so they merged a single commit with a garbage commit message which is basically just an error message. So the intent would be to go through the commit messages of the PR (chances are there's only one but still...) and see if they make sense.

I guess it kinda works alongside the idea of linting commit messages?

**Comment by Figforth** [comment]
Artichoke!!!! Mr. Crowley!!!

**Comment by Figforth** [comment]
> [odoo/odoo@ce67acc](https://github.com/odoo/odoo/commit/ce67acc1ba4a91682e2d4ebbbdfb96b1be87b8df) reported by @JKE-be
> 
> * [ ]  don't stage if any of the PR's commits contains a conflict message
> * [ ]  remove approver's review rights on the PR? there's no "negative delegations" so users with "persistent" review rights can't easily have them removed

https://abcnews.go.com/US/scientists-investigate-blue-oceanic-mystery-off-florida-coast/story?id=71919756

**Comment by xmo-odoo** [comment]
#505 should largely fix this issue (alongside the older #204) as it should prevent easily merging a squashed conflict commit (at least when there's more than one author on the PR).
