### ISSUE TITLE
[Question] Can I download source code from runbot?

### ISSUE THREAD

**Issue by obayit** [odoo/runbot#385]
I noticed that the source code for repositories is in the `runbot/static` directory.
Can anyone download source files using normal URLs?
I did install runbot and have private repositroies that shouldn't be seen by anyone unauthorized. I hope it is protected somehow!

**Comment by d-fence** [comment]
Hello, you have ton [configure](http://www.odoo.com/documentation/13.0/setup/deploy.html#security) your web server accordingly.

**Comment by obayit** [comment]
Well ...
For now, in my nginx `server` block I did the following:
```
  location ~* ^/runbot/static/(build|docker|nginx|repo|sources).*$ {
    return 444;
  }

```
Log files inside `build/` might be needed, but for now that will work.
