### ISSUE TITLE
Dropdown closed on scroll

### ISSUE THREAD

**Issue by msh-odoo** [odoo/runbot#386]
Tested on runbot.odoo.com

When I go to Gear icon on where we have lots of items in dropdown, as soon as I try to go to bottom of the dropdown to apply my changes by clicking save button, dropdown get closed due to scroll event, it seems legit to close dropdown when scrolling but dropdown itself should have vertical scrollbar when there are too many items.

**Comment by Xavier-Do** [comment]
Those are the default bootstrap dropdown, I don't think there are able to handle so much elements. Anyway, I have no problem to display all items at one without scrolling, is it blocking for you? 
I'll need to rethink this menu but it isn't a priority.
