### ISSUE TITLE
Actually ignore unknown commands

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#390]
https://github.com/odoo/odoo/pull/50885#issuecomment-661084647

**Comment by mart-e** [comment]
or at least concatanate all the ignored arguments so we can still make fun sentences

**Comment by Xavier-Do** [comment]
@mart-e you can't make fun of robodoo

**Comment by xmo-odoo** [comment]
> @mart-e you can't make fun of robodoo

indeed robodoo is srs bizns.
