### ISSUE TITLE
How to make pip cache downloaded packages.

### ISSUE THREAD

**Issue by obayit** [odoo/runbot#394]
pip packages are [downloaded](http://runbot48.odoo.com/runbot/static/build/4093070-12-0/logs/install_all.txt) in very new build (e.g: if the runbot is running on 13.0, and the build is for 12.0). 

How to make it cache the downloaded files?

If the packages are cached it will improve the build time, and save a bit of network resources.

**Comment by Xavier-Do** [comment]
Caching old pip packages is a good idea but pip packages update was never a big deal for us so we never investigated a solution for that. I don't know if there is an easy way, maybe @d-fence will have an idea.

**Comment by Xavier-Do** [comment]
Pip are cached in docker images (docker image contains base pip for each versions) and only diff should be installed.
After merging the docker registry, we plan to have a "per requirement" docker images, meaning the the docker image may be build with requirement once when the requirements of the branch are different. We even plan to remove requirements from docker images and from build to only use debian control only, and test requirements during nightly. We don't have plan to cache pip another way for now runbot side.
