### ISSUE TITLE
Problems in MY configuration following the steps according to README.md

### ISSUE THREAD

**Issue by rigo1985** [odoo/runbot#396]
I am trying to configure runbot by following the README.md, updated in the last commit and I am getting this error.

![2020-09-11_09-11_runbot](https://user-images.githubusercontent.com/10016548/92883575-48ba1f00-f411-11ea-912a-a440e2f033ae.png)

Can you help me. I don't know what I'm missing

Thanks

**Comment by Xavier-Do** [comment]
It look like your user doesn't have the right to connect to postgres database. 

Are you using a specific user to run runbot? Can you try to connect manually. `psql postgres`

**Comment by rigo1985** [comment]
[SOLVED] 
![2020-09-13_runbot](https://user-images.githubusercontent.com/10016548/93023333-7f995c00-f5ee-11ea-8566-59a95a56970c.png)

Thanks for your help.
Some time ago I had changed postgres configuration (pg_hba.conf), removing 'peer' for 'md5' and had added password
