### ISSUE TITLE
PR dashboard doesn't seem to take CI overrides in account properly

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#433]
![Screenshot_2020-11-27 odoo odoo#62380 - Odoo](https://user-images.githubusercontent.com/7571158/100437200-b84eba80-30a0-11eb-8169-9195e2abb14e.png)
![Screenshot_2020-11-27 view_pull_request mergebot odoo com](https://user-images.githubusercontent.com/7571158/100437193-b553ca00-30a0-11eb-8793-a9d405109675.png)

Also while at it, maybe if a message contains a CI override use the rest of the comment as description so we don't have to track down the justification given for the override? Alternatively, add a sub-command for providing the description / justification? /cc @odony @mart-e

**Comment by tivisse** [comment]
![image](https://user-images.githubusercontent.com/8435879/152495943-33af1bc0-220c-4b05-805e-5e8b47f844ba.png)

LIAR !!!
