### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#438]
Be me.

Be browsin' github

![Screenshot from 2020-12-07 07-49-11](https://user-images.githubusercontent.com/7571158/101318558-d5ce1200-3860-11eb-96c2-c0de29a17d46.png)

nice.jpg

switch to runbot

![Screenshot from 2020-12-07 07-49-31](https://user-images.githubusercontent.com/7571158/101318611-e8484b80-3860-11eb-92a8-0ddbede646ee.png)

![my_eyes](https://user-images.githubusercontent.com/7571158/101318748-1f1e6180-3861-11eb-8f61-f1e838b67d3e.gif)

Thank you for coming to my ted talk.

**Comment by Elkasitu** [comment]
I'm Ray William Johnson and I approve this message :+1:

**Comment by xmo-odoo** [comment]
PS: browsers expose [a CSS `@media` property to know whether the user's system is configured in light or dark mode](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme):
```css
@media (prefers-color-scheme: light) {
    // if light theme selected
}
@media (prefers-color-scheme: dark) {
    // if dark theme selected
}
```
Light / dark theming is OS-specific and can be weird e.g. in Mint it's controlled by the "Controls" section of the theme.
