### ISSUE TITLE
New integration modes & controls

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#48]
Currently, the mergebot has 3(.5) modes of integration with limited explicit control knobs:

* if only a single commit, squash it
* if 2+ commits, rebase-then-merge
* if `rebase-`, just merge (unless the head of the PR is a merge commit at which point it can do something more complex).

Some people have apparently expressed interest in the ability to explicitly ask for a rebase-and-ff, and possibly also explicitly squashing any number of commits?

/cc @qdp-odoo @tde-banana-odoo @rco-odoo @antonylesuisse @odony

**Comment by qdp-odoo** [comment]
yup,

my opinion is that the default behavior should be:
* if there's one commit: rebase it
* if there's more than one commit: I should be able to choose if I want to rebase them with or without merge commit (for me, the default should be without) or even squash them in a single commit

Optionally, I'd like also to be able to amend the commit message that would be used, in case of a PR resulting in a single commit.

**Comment by tde-banana-odoo** [comment]
How is it possible to have that kind of commit https://github.com/odoo/odoo/commit/ddc531a35a5d5fecb17c760b214e97581a7e76bb ? We lost the author somewhere ... or was it someone logged as robodoo?

**Comment by xmo-odoo** [comment]
> How is it possible to have that kind of commit odoo/odoo@ddc531a ? We lost the author somewhere ... or was it someone logged as robodoo?

It's a merge commit? Who else would the author be?

**Comment by odony** [comment]
> How is it possible to have that kind of commit [odoo/odoo@ddc531a](https://github.com/odoo/odoo/commit/ddc531a35a5d5fecb17c760b214e97581a7e76bb) ? We lost the author somewhere ... or was it someone logged as robodoo?

You're looking for the ff-only merge mode, where such useless merge commits do not exists ;-)

**Comment by odony** [comment]
Do we need the `rebase-` command? Does anyone use it? Is it meant to preserve commit signatures?

**Comment by xmo-odoo** [comment]
> Do we need the rebase- command? Does anyone use it? Is it meant to preserve commit signatures?

Forward ports.

**Comment by tde-banana-odoo** [comment]
> > How is it possible to have that kind of commit [odoo/odoo@ddc531a](https://github.com/odoo/odoo/commit/ddc531a) ? We lost the author somewhere ... or was it someone logged as robodoo?
> 
> It's a merge commit? Who else would the author be?

Ok, those guys should learn to use the merge tag when creating a PR.

To answer your question: the one who added r+. It is interesting to know who validated the merge. Otherwise you have to find the PR, read the discussion, ... I like to know who validated a merge, notably when dealing with tasks done by newcomers for example.

**Comment by odony** [comment]
> Forward ports.

Forward ports really ought to be handled outside of the normal PR flow. I see very little point in making dozens of useless PRs that nobody will ever look at except @KangOl. He automates the creation of the PR, the manual commands (`rebase`, `priority`, etc), and often forces the commit anyway. At that point, he could  stop using mergebot entirely. Branches + runbot are quite enough. Seriously: https://github.com/odoo/odoo/pull/28013


> Ok, those guys should learn to use the merge tag when creating a PR.

They probably did not even realize this would create a merge commit. The mergebot should be the one ensuring that merge commits are properly tagged.


> To answer your question: the one who added r+. It is interesting to know who validated the merge. Otherwise you have to find the PR, read the discussion, ... I like to know who validated a merge, notably when dealing with tasks done by newcomers for example.

What if there are several reviewers, as should ultimately be the case? My suggestion is that each commit (even when squashed) gets "Reviewed-By: @foo-odoo" trailers, [following the kernel convention](https://git.wiki.kernel.org/index.php/CommitMessageConventions).

**Comment by odony** [comment]
My wishlist:

```
# Mono-commit PR
@robodoo r+         rebase + merge ff-only (implies ff+)
@robodoo r+ ff+     rebase + merge ff-only
@robodoo r+ ff-     merge with explicit commit (rebase?)

# Multi-commit PR
@robodoo r+              merge with explicit commit (rebase?) (implies ff-) 
@robodoo r+ ff-          merge with explicit commit (rebase?) 
@robodoo r+ ff+          rebase + merge ff-only
@robodoo r+ squash+      squash + merge ff-only (implies ff+)
@robodoo r+ squash+ ff-  squash + merge with explicit commit
```

@qdp-odoo not sure we should use git commands, given that these instructions are mere "votes", and there should be multiple reviewers required in some cases. How about a way to override the commit message with the PR description, for single commit PRs too? Something like this:

```
# Mono-commit PR
@robodoo r+               rebase + merge ff-only
@robodoo r+ force-msg+    rebase + override commit msg + merge ff-only
```

**Comment by xmo-odoo** [comment]
> Forward ports really ought to be handled outside of the normal PR flow. 

Forward ports are one of the main sources of branch breakages if not the main source period. robodoo already caught branch-breaking forward ports multiple times.

> They probably did not even realize this would create a merge commit. The mergebot should be the one ensuring that merge commits are properly tagged.

Would make way more sense to have a different status check doing that, this doesn't really belong in robodoo. We need a status check to build the docs anyway (I've been looking at doing *that* on travis and it looks like it would work, sadly pylint does not).

> What if there are several reviewers, as should ultimately be the case? My suggestion is that each commit (even when squashed) gets "Reviewed-By: @foo-odoo" trailers, following the kernel convention.

That's possible. Robodoo already adds a "closes" annotation to link back to the PR, it could add an "Acked-By" or "Reviewed-By" annotation as well. But that requires storing the reviewer so some development. Can you open a separate issue for that?

> @robodoo r+ squash+ ff-  squash + merge with explicit commit

I don't know that this one makes a lot of sense.

**Comment by antonylesuisse** [comment]
I rather have explicit commands: We get rid of r+ and only use an action verb

# Mono/Multi-commit no diffrence
@robodoo ff  (or rebase)
@robodoo merge
@robodoo squash

**Comment by odony** [comment]
> I rather have explicit commands: We get rid of r+ and only use an action verb

How do you handle multiple reviewers, or overriding a prior command, then? The + and - suffixes seem to better indicate that you're voting towards an outcome, not executing a git command.

**Comment by qdp-odoo** [comment]
I tend to agree with Antony here

> How do you handle multiple reviewers, 

You don't need. Real use cases where we're in that situation are not numerous anyway.
As far as I know, it's currently not the case since a single r+ is enough to trigger the mergebot whatever the number of requested reviewers (so, currently, it's not a vote)... 

> or overriding a prior command, then? 

why not another command ? like `stop`, `block` or `reject` ?

**Comment by xmo-odoo** [comment]
> You don't need.

Yeah you do. It's not something we need or support *now*, but it's something people have asked about, and I'm not going to close/block that path for no reason. Furthermore things like delegation, retrying/re-reviewing, … configuration and reviewring are orthogonal concerns.

**Comment by qdp-odoo** [comment]
@xmo-odoo then you'll check the reviewers' approvals to block or reject the PR, there's no need to handle this with commands

**Comment by KangOl** [comment]
Has it been deployed?

Note that the README hasn't been updated.

**Comment by KangOl** [comment]
Yes, it has.
