### ISSUE TITLE
[runbot] Markdown code formating

### ISSUE THREAD

**Issue by Xavier-Do** [odoo/runbot#481]
Ci style and security will sometimes log code like `__init__` that isn't managed as code an appears as __init__
- text inside `` shouldn't be formated
- text quoted from code like method name should be always put inside ``

**Comment by xmo-odoo** [comment]
> text inside `` shouldn't be formated

AFAIK that's already the case in every markdown implementation, text inside backticks and code blocks (whether indented or fenced code blocks) is literal.

Of course that assumes you're not embedding backticks inside code spans, in that case you need tricks like [weird-ass delimiter sequences](https://spec.commonmark.org/0.29/#code-spans) or [alternate fence characters](https://spec.commonmark.org/0.29/#fenced-code-blocks). But in both cases this is easy enough to do programmatically, I'd say. Though compatibility of the markdown implementation with commonmark's methods would have to be checked.

For indented code blocks this is not an issue.

**Comment by Xavier-Do** [comment]
```python
import markdown
>>> markdown.markdown('**x**')
'<p><strong>x</strong></p>'
```
Ok, I don't need this stupid `<p>` but we could manage that

```python
>>> markdown.markdown('[link](https://wwww.somewhere.com) ')
'<p><a href="https://wwww.somewhere.com">link</a> </p>'
```
Once again, at least it works.

```python
>>> markdown.markdown('~~x~~')
'<p>~~x~~</p>'
```
Not standard but sad, we need an extra for this one
```python
>>> markdown.markdown('__x__')
'<p><strong>x</strong></p>
```
So it is the same ass `**`, we prefer the discord underline for this one. 

```python
markdown.markdown('@icon-file-text-o')
'<p>@icon-file-text-o</p>'
```
Of course it doesn't work, it's not standard at all.

More exceptions than working cases, we decided to add a custom pseudo markdown.
