### ISSUE TITLE
Getting "500: Internal Server Error" when accessing <host>/runbot/0

### ISSUE THREAD

**Issue by MohammadSalek** [odoo/runbot#514]
There seems to be an issue when slugifying url:

When trying to reach: https://runbot.odoo.com/runbot/0 or https://runbot.odoo.com/runbot/r-d-0 the response is:
```
500: Internal Server Error
Traceback

Traceback (most recent call last):
  File "/home/odoo/runbot/odoo/addons/http_routing/models/ir_http.py", line 548, in _postprocess_args
    _, path = rule.build(arguments)
  File "/usr/lib/python3/dist-packages/werkzeug/routing.py", line 809, in build
    add(self._converters[data].to_url(values[data]))
  File "/home/odoo/runbot/odoo/addons/http_routing/models/ir_http.py", line 257, in to_url
    return slug(value)
  File "/home/odoo/runbot/odoo/addons/http_routing/models/ir_http.py", line 91, in slug
    raise ValueError("Cannot slug non-existent record %s" % value)
ValueError: Cannot slug non-existent record runbot.project()
```
Reaching any other url like: https://runbot.odoo.com/runbot/r-d-1 gives response with 200 status code . Or by reaching out to a non-existent url like https://runbot.odoo.com/runbot/100000000000 the response is with a 404 status code. Also there are responses with 403 status code, but no other url seems to cause an internal error other than `<host>/runbot/0 `.

Error is raised from the `slug()` function from `runbot/runbot/controllers/frontend.py` which is imported from `odoo.addons.http_routing.models.ir_http` file.

**Comment by Xavier-Do** [comment]
> If it's not a valid URL, and it does not exist, then it's about the client who tries to reach there in the first place. Therefore I argue it's a 400-type error. (client's error rather than server's)
> Besides, having the response in 500 error is generally an indicator of bad development in back-end.

It's not runbot related.  The route is declared as `'/runbot/<model("runbot.project"):project>'` and the error occurs during the slugification of the url.

As an example, https://9689860-master-all.runbot52.odoo.com/shop/0 will give the same error.

We'll talk about that since we have some http/routing refactor in progress but to be honnest it doesn't look critical, and changing that in stable is not a good idea.
