### ISSUE TITLE
Using commits from `master` for other versions

### ISSUE THREAD

**Issue by obayit** [odoo/runbot#546]
I get the following build:
![screenshot-ghaya-it-laptop_8099-2021 10 10-13_16_40](https://user-images.githubusercontent.com/20386024/136693384-c1e68da1-499d-4694-99ca-2fe099a60f99.png)

Instead of using a commit from `odoo/odoo` on branch `11.0` it is using latest commit from `master` branch.
What could be the cuase of this? and how to fix it?

**Comment by Xavier-Do** [comment]
Difficult to say like that but the most obvious answer would be that you don't have a bundle 11.0 that would be detected as a base, so the version computed for this bundle is master (fallback for unkown version). You should check the bundle view you way have a warning.
