### ISSUE TITLE
Image build failed

### ISSUE THREAD

**Issue by obayit** [odoo/runbot#563]
I had to run the build command manually: `docker build --tag odoo:DockerDefault .`, it works until step no. 11. Then it gives the following error `E: Unable to correct problems, you have held broken packages.`
![Screenshot from 2021-12-23 14-31-03](https://user-images.githubusercontent.com/20386024/147241273-10372826-e8cf-41a8-bc98-db9bcce8f739.png)

**Comment by obayit** [comment]
Closing this because it is probably only happening in my end. Just found that the Dockerfile is generated with qweb views and it is different for each version: `master`, `15.0`, ...etc

**Comment by yustas147** [comment]
I also had this issue. 
Fixed it in template file runbot/templates/dockerfile.xml
![Screenshot_29](https://user-images.githubusercontent.com/16666239/150946334-3e4a64ca-d50d-4f74-8ea4-d0891e3a6a84.png)
After fixing docker build works fine

**Comment by obayit** [comment]
I managed to build the image for version `11.0` after importing the Dockerfile from older versions of runbot and modifying it a bit, also for some reason I was only able to successfully build the image with BuildKit, aka running the command
`DOCKER_BUILDKIT=1 docker build ...`
