### ISSUE TITLE
No base head found for repo .... (repoRunbotfork1)

### ISSUE THREAD

**Issue by yustas147** [odoo/runbot#574]
installed and configured runbot 5.1 (using Readme.md)
made fork of odoo/runbot (git@github.com:yustas147/runbot.git)
made commit to forked
no errors in odoo logfile
-------
Want to see any running testing process: no success.

Cannot get active building process run
![Screenshot_30](https://user-images.githubusercontent.com/16666239/150965641-9fc9c834-ed93-4a4c-8ef4-c2a95c50c18b.png)
![Screenshot_31](https://user-images.githubusercontent.com/16666239/150966688-814d00de-5c2e-4a04-bdd0-323294e968e3.png)
![Screenshot_32](https://user-images.githubusercontent.com/16666239/150966834-ffd9f354-f3f2-454a-86a4-2b2f99b344a7.png)
![Screenshot_33](https://user-images.githubusercontent.com/16666239/150966959-21ed16b0-0c34-4385-86de-8b81331dec70.png)
![Screenshot_34](https://user-images.githubusercontent.com/16666239/150967163-8153f2ec-cd5b-457c-918b-1e1f0f8d9f0e.png)
------
What am I doing wrong?

**Comment by Xavier-Do** [comment]
I'm not sure of what your problem is but it looks like your builds are not taken.

The runbot is more and more focussed on using different process, and it looks like you are missing the builder.

I would suggest you to check in the settings if `Schedule builds` is checked
