### ISSUE TITLE
filter out some warnings on runbot builds

### ISSUE THREAD

**Issue by OKT96** [odoo/runbot#602]
For example:
![image](https://user-images.githubusercontent.com/85667041/162694521-151b749a-6a54-4b78-a8a8-d4a7a02ae84a.png)

Because of this one warning the whole batch gets also yellow/orange colored. Is there a way to filter out certain known warnings? so that the batch gets green

**Comment by Xavier-Do** [comment]
Sorry for the delay.

There is no mechanism for that in runbot, it is intended to have a build in error if there is a warning/error log.
This should be managed by fixing the code (avoiding deprecated walls  or muting specific warnings).
To mute a specific warning you may want to use `warnings.filterwarnings()`, there are examples in netsvc.py
