### ISSUE TITLE
Upgrade Module

### ISSUE THREAD

**Issue by Yousif-Mobark** [odoo/runbot#620]
Hi every one !

i want to let the run bot  upgrade the module directly if the module version number increase .

#Also i want to implement this on my production environment any tips  ?.

**Comment by Xavier-Do** [comment]
I don't understand what you are trying to achieve, can you give us more details?

**Comment by Yousif-Mobark** [comment]
In odoo.sh  if you add something in the view.xml for example and you want
push your code . You can increase the version number in module manifest  .


And it will make upgrade to the module automatically.


Can I achive that with runbot?

**Comment by Xavier-Do** [comment]
Runbot will install a new database from scratch when you push a build, there is no reuse of a database from a previous build except to test migrations, but we always start from the save of a clean database, not a running one.

What you want to do may be possible with python steps, identifying the database you want to restore, restoring it and updating it but there is now easy to use recipe for that. This is not the purpose of runbot :)
