### ISSUE TITLE
Create pre-docker tag?

### ISSUE THREAD

**Issue by hbrunn** [odoo/runbot#76]
would it be possible to tag commit 549452f12dafd5b74ef5a0cb924da1c3f0edc964 so that community runbot code can refer to that for testing until we've adapted that to current changes? Thanks in advance!

**Comment by xmo-odoo** [comment]
Tagged both the last pre-docker revision (`pre-docker`) and the first docker revision (`dockerized`).

**Comment by hbrunn** [comment]
yay, thanks a lot!
