### ISSUE TITLE
Odoo 17

### ISSUE THREAD

**Issue by schwahue** [odoo/runbot#829]
Hi guys, is runbot branch 17.0 adapted for Odoo 17?

**Comment by Xavier-Do** [comment]
No, we will make it the default branch once it is. (for runbot)

Shouldn't take to much time but we have some priority before that (docker registry mainly).
We have some step to reach before making it the default branch:
- [ ] make tests green
- [ ] test it manually (fix broken layouts)
- [ ] make migration work
- [ ] test the production database 

I'll work a little on the first and maybe second point this afternoon.

**Comment by Xavier-Do** [comment]
17.0 is now the default branch
