### ISSUE TITLE
Surface / clarify / better expose modify/delete conflict

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#896]
This is a broad issue if mostly hit by the JS team I would think:

- in branch A, have a file f1
- in branch B (descendant of A), delete f1
- update f1 in a PR of A
- when PR-A is forward-ported, it's going to "resurrect" f1, with a modify/delete conflict *but no conflict marker*

Example: odoo/odoo#167615 where the conflict was notified but odoo/odoo@c237341b44bb3b15b9f2b2ddb080d76567e7062c clearly shows that addons/web/static/tests/legacy/views/kanban/kanban_view_tests.js is just added

Because there are no conflict markers it won't be blocking any sort of CI or anything, the PR will be detached and there will be an error message from the forwardbot, but it will still be easy to miss that the file was reintroduced, and a dev can easily fix other conflicts, not notice the new file, and merge that, reintroducing a weird dead file.

That's not great.

Various possible options (which may be combined?):
- ~~try to find if git can surface modfy/delete conflicts better~~ couldn't find anything, and SO didn't surface anything either
  - manually insert conflict marker in the lazarus file if no?
- parse git's conflict output to make a note of modify/delete conflicts
- compare the total diffstats, it should be possible for a cherrypick to have (a lot) less lines than the original, but is there any way it has *more*?
- have the mergebot keep track of conflicting files (mapping files to blobs), and block approval / progress until they've all been replaced or removed?
  - that might actually be a pretty good one: on SYNC trigger a cron to retrieve the HEAD commit and see if the CONFLICT blobs are still present, remove those which are not from the list of conflicts; on r+ check that the head is sync'd and verify that the CONFLICT list is empty.
- have the mergebot check files added and if they match between source and target (`show --name-status`, or `show --diff-filter=A --name-only` lists only added files): I don't see a scenario where a file can be added by a merge / cherrypick without *that exact same file* being added by the source

**Comment by xmo-odoo** [comment]
@aab-odoo should be deployed, hopefully the next such conflict will be easier to notice.

**Comment by aab-odoo** [comment]
Thanks @xmo-odoo
