### ISSUE TITLE
Support shifting commits into branches without PR

### ISSUE THREAD

**Issue by xmo-odoo** [odoo/runbot#926]
Suggestion of @Xavier-Do after transifex was mean again (kept pushing to 15.0 and 16.0 yesterday and thus cancelled essentially every staging): for the safer stuff like transifex, rather than require a full blown PR the mergebot could have a queue of commits to cherrypick, which it would simply shift into stagings. Two options were considered:

- shift in / add those commits when creating the staging, the advantage is that those commits would be tested, the drawback is that it's hard to decide what would happen if the staging fails, whether because of a false positive or because the commit happens to be broken (which has happened once or twice w/ transifex but is really uncommon all things considered)
- shift in *after* the staging, just before pushing to the reference branch, this reduces the delay if there's already a staging going on, but only if the staging is successful
- or a combination of the two: just before / after checking if there's stuff to stage *but separately*, shift all the commits into the upstream branch directly, then do the staging

The latter seems like it combines all the advantages of the other two, and limits the drawbacks, and can furthermore allow immediate updates by cancelling the current staging for the branch (thus limiting the risks of conflicts). Eventually it could also allow suppressing the runbot build because e.g. it's not super useful to create a runbot build just because we merged translations.

TBD: how to tell the mergebot about those commits? Backend UI? API? Other?

/cc @d-fence @mart-e @beledouxdenis 

A patch version should be supported for convenience / scripting, even though it will require working copies / worktrees after we managed to expunge them from the mergebot (neither `git am` nor `git apply` support applying patches to git trees, sadly).

**Comment by Xavier-Do** [comment]
> TBD: how to tell the mergebot about those commits? Backend UI? API? Other?

-> backend ui in all cases, api via rpc calls? or maybe add a token authentication for simplicity?
