### ISSUE TITLE
USER ERROR: Access Denied from Location - please get in touch with the runbot team or use a development database

### ISSUE THREAD

**Issue by Z1YAD-M** [odoo/runbot#933]
I logged on to Odoo v16 active all database
![image](https://github.com/user-attachments/assets/d82c5a60-b43c-40b5-a029-de53cf5d0726)
![image](https://github.com/user-attachments/assets/4bf6407c-ba3b-4641-841e-1bea7319d877)

I wanted to play with automated actions, and I got this error
![image](https://github.com/user-attachments/assets/b664d7cb-fcbf-42f4-a94e-7a1f547c2a50)

I even logged in as a superuser, no difference. Found nothing online about this. What is the cause?

**Comment by Xavier-Do** [comment]
Yeah unfortunately we had to disable some actions in runbot main builds because of abuse (sticky branches with a star). The limitation is not present on dev branches.
